-- EduSmart AI
-- Oracle Database Setup


-- Create Table

CREATE TABLE student_performance (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR2(100) NOT NULL,
    roll_no VARCHAR2(20) UNIQUE NOT NULL,
    attendance NUMBER(5,2),
    python_marks NUMBER(5,2),
    web_marks NUMBER(5,2),
    plsql_marks NUMBER(5,2),
    average_marks NUMBER(5,2),
    grade VARCHAR2(5),
    ai_recommendation VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Function to Calculate Average

CREATE OR REPLACE FUNCTION calculate_average(
    p_python NUMBER,
    p_web NUMBER,
    p_plsql NUMBER
)
RETURN NUMBER
IS
    v_average NUMBER;
BEGIN
    v_average := (p_python + p_web + p_plsql) / 3;
    RETURN ROUND(v_average, 2);
END;
/


-- Procedure to Update Performance

CREATE OR REPLACE PROCEDURE update_performance(
    p_roll_no VARCHAR2
)
IS
    v_average NUMBER;
    v_grade VARCHAR2(5);
BEGIN

    SELECT (python_marks + web_marks + plsql_marks) / 3
    INTO v_average
    FROM student_performance
    WHERE roll_no = p_roll_no;

    IF v_average >= 90 THEN
        v_grade := 'A+';
    ELSIF v_average >= 80 THEN
        v_grade := 'A';
    ELSIF v_average >= 70 THEN
        v_grade := 'B';
    ELSIF v_average >= 60 THEN
        v_grade := 'C';
    ELSIF v_average >= 50 THEN
        v_grade := 'D';
    ELSE
        v_grade := 'F';
    END IF;

    UPDATE student_performance
    SET average_marks = ROUND(v_average, 2),
        grade = v_grade
    WHERE roll_no = p_roll_no;

    COMMIT;
END;
/


-- Trigger to Validate Marks

CREATE OR REPLACE TRIGGER validate_student_marks
BEFORE INSERT OR UPDATE ON student_performance
FOR EACH ROW
BEGIN

    IF :NEW.attendance < 0 OR :NEW.attendance > 100 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Attendance must be between 0 and 100'
        );
    END IF;

    IF :NEW.python_marks < 0 OR :NEW.python_marks > 100 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Python marks must be between 0 and 100'
        );
    END IF;

    IF :NEW.web_marks < 0 OR :NEW.web_marks > 100 THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            'Web marks must be between 0 and 100'
        );
    END IF;

    IF :NEW.plsql_marks < 0 OR :NEW.plsql_marks > 100 THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'PL/SQL marks must be between 0 and 100'
        );
    END IF;

END;
/


-- Procedure to Add Student

CREATE OR REPLACE PROCEDURE add_student(
    p_student_name VARCHAR2,
    p_roll_no VARCHAR2,
    p_attendance NUMBER,
    p_python_marks NUMBER,
    p_web_marks NUMBER,
    p_plsql_marks NUMBER
)
IS
    v_average NUMBER;
    v_grade VARCHAR2(5);
BEGIN

    v_average :=
        (p_python_marks + p_web_marks + p_plsql_marks) / 3;

    IF v_average >= 90 THEN
        v_grade := 'A+';
    ELSIF v_average >= 80 THEN
        v_grade := 'A';
    ELSIF v_average >= 70 THEN
        v_grade := 'B';
    ELSIF v_average >= 60 THEN
        v_grade := 'C';
    ELSIF v_average >= 50 THEN
        v_grade := 'D';
    ELSE
        v_grade := 'F';
    END IF;

    INSERT INTO student_performance (
        student_name,
        roll_no,
        attendance,
        python_marks,
        web_marks,
        plsql_marks,
        average_marks,
        grade
    )
    VALUES (
        p_student_name,
        p_roll_no,
        p_attendance,
        p_python_marks,
        p_web_marks,
        p_plsql_marks,
        ROUND(v_average, 2),
        v_grade
    );

    COMMIT;

END;
/


-- Sample Student Data

INSERT INTO student_performance
(student_name, roll_no, attendance, python_marks, web_marks, plsql_marks,
 average_marks, grade)
VALUES
('Rahul Kumar', 'ES001', 82, 75, 68, 80, 74.33, 'B');


INSERT INTO student_performance
(student_name, roll_no, attendance, python_marks, web_marks, plsql_marks,
 average_marks, grade)
VALUES
('Aman Kumar', 'ES002', 88, 82, 76, 84, 80.67, 'A');


INSERT INTO student_performance
(student_name, roll_no, attendance, python_marks, web_marks, plsql_marks,
 average_marks, grade)
VALUES
('Rohit Kumar', 'ES003', 90, 85, 78, 88, 83.67, 'A');


INSERT INTO student_performance
(student_name, roll_no, attendance, python_marks, web_marks, plsql_marks,
 average_marks, grade)
VALUES
('Priya Kumar', 'ES004', 92, 88, 85, 90, 87.67, 'A');


INSERT INTO student_performance
(student_name, roll_no, attendance, python_marks, web_marks, plsql_marks,
 average_marks, grade)
VALUES
('Neha Sharma', 'ES005', 68, 75, 80, 72, 75.67, 'B');


COMMIT;


-- Check Data

SELECT
    student_id,
    student_name,
    roll_no,
    attendance,
    average_marks,
    grade
FROM student_performance;